services:
  frontend:
    build: ./frontend
    volumes:
      - frontend_build:/app/build

  backend:
    build: ./backend
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
      - START_Y=50
      - START_X=50
      - ROTATION=0
      - IMAGE_SIZE=4096
      - CAMERA_ID=0
      - NVIDIA_VISIBLE_DEVICES=all
    devices:
      - /dev/video0
      - /dev/video1
      - /dev/video2
      - /dev/video3
    volumes:
      - /usr/local/cuda:/usr/local/cuda
      - frontend_build:/app/build
    ports:
      - 9000:9000
    depends_on:
      - frontend

volumes:
  frontend_build: